title: "DRON"
description: "El hub de drones FPV."
baseurl: "" # Deja vacío si el sitio está en usuario.github.io o ajusta si está en usuario.github.io/repositorio.
url: "http://localhost:4000/" # Cambia esta URL a la de tu sitio.
theme: minima # Tema básico que viene con Jekyll.
plugins:
  - jekyll-feed
  